version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: triptweak-postgres
    environment:
      POSTGRES_DB: bookingdb
      POSTGRES_USER: booking_user
      POSTGRES_PASSWORD: booking_pass
    ports:
      - "5432:5432"
    volumes:
      - triptweak_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U booking_user -d bookingdb"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  triptweak_pgdata:
